# # modified code from https://www.youtube.com/watch?v=N9hRhcHpg1c
# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: vue-app
#     ports:
#       - 8080:80
#     volumes:
#      - .:/app
  
#   nginx:
#     image: nginx:alpine
#     container_name: nginx-app
#     volumes:
#     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - 80:80
#     depends_on:
#       - app

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
