# Modified code from https://youtu.be/9ZEbJT36-Uk?si=I2Xe1PSKtExLT2rR

version: "3.4"

networks:
  dev:
    driver: bridge

services:
  netbackend:
    image: docker.io/library/netbackend
    depends_on:
      - "postgresTest"
      - "postgresCustomerOne"
      - "postgresCustomerTwo"
    container_name: netbackend
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=password;Server=postgresTest;Database=postgresTestDB;Pooling=true;Port=5432;
      - ConnectionStrings__CustomerOneConnection=User ID=postgres;Password=password;Server=postgresCustomerOne;Database=postgresCustomerOneDB;Pooling=true;Port=5432;
      - ConnectionStrings__CustomerTwoConnection=User ID=postgres;Password=password;Server=postgresCustomerTwo;Database=postgresCustomerTwoDB;Pooling=true;Port=5432;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  postgresTest:
    image: postgres:latest
    container_name: postgresTest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresTestDB
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./.containers/postgresTestDb:/var/lib/postgresql/data
    networks:
      - dev

  postgresCustomerOne:
    image: postgres:latest
    container_name: postgresCustomerOne
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresCustomerOneDB
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./.containers/postgresCustomerOneDb:/var/lib/postgresql/data
    networks:
      - dev

  postgresCustomerTwo:
    image: postgres:latest
    container_name: postgresCustomerTwo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresCustomerTwoDB
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - ./.containers/postgresCustomerTwoDb:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
